### ISSUE TITLE
Support two node formation

### ISSUE THREAD

**Issue by serkancoban** [Navid2zp/citus-failover#1] opened 2021-06-12 13:22 UTC
Currently isPrimary() is checking gaolstate 'primary' only. This makes citus-failover not work as expected in two node formations.
goalstate may be checked against 'primary' or 'wait_primary'. Other solution might be making a new configuration parameter for two node formations and checking goalstate against 'wait_primary' only when configuration key is set.

**Comment by Navid2zp** [comment] 2021-06-12 15:00
Hello,

I'm not sure if I understand what you mean. `isPrimary()` checks for `primary` status which must be the `goalstate` for a node to be primary. Is this not the case in a two-node formation? a node with `goalstate=wait_primary` is not a primary node.

**Comment by serkancoban** [comment] 2021-06-12 16:38
In two-node formation when secondary is not available, primary status is wait_primary. We are using two-node formations and citus-failover does not take action in this case.

**Comment by serkancoban** [comment] 2021-06-12 16:56
Below you can see the states, I stopped worker03 which was primary.

postgres@pg-failover:~/13$ pg_autoctl show state --formation worker3-4
   Name |  Node |     Host:Port |          LSN |   Connection |       Current State |      Assigned State
--------+-------+---------------+--------------+--------------+---------------------+--------------------
node_13 |    13 | worker03:5432 | 14D/E54FA8F0 |   read-write |             primary |             primary
node_14 |    14 | worker04:5432 | 14D/E54FA8F0 |    read-only |           secondary |           secondary

root@worker03:~# systemctl stop pgautofailover.service

postgres@pg-failover:~/13$ pg_autoctl show state --formation worker3-4
   Name |  Node |     Host:Port |          LSN |   Connection |       Current State |      Assigned State
--------+-------+---------------+--------------+--------------+---------------------+--------------------
node_13 |    13 | worker03:5432 | 14D/E54FA8F0 | read-write ! |             primary |             demoted
node_14 |    14 | worker04:5432 | 14D/E54FE998 |   read-write |        wait_primary |        wait_primary

**Comment by Navid2zp** [comment] 2021-06-12 17:27
> Below you can see the states, I stopped worker03 which was primary.
> 
> postgres@pg-failover:~/13$ pg_autoctl show state --formation worker3-4
> Name | Node | Host:Port | LSN | Connection | Current State | Assigned State
> --------+-------+---------------+--------------+--------------+---------------------+--------------------
> node_13 | 13 | worker03:5432 | 14D/E54FA8F0 | read-write | primary | primary
> node_14 | 14 | worker04:5432 | 14D/E54FA8F0 | read-only | secondary | secondary
> 
> root@worker03:~# systemctl stop pgautofailover.service
> 
> postgres@pg-failover:~/13$ pg_autoctl show state --formation worker3-4
> Name | Node | Host:Port | LSN | Connection | Current State | Assigned State
> --------+-------+---------------+--------------+--------------+---------------------+--------------------
> node_13 | 13 | worker03:5432 | 14D/E54FA8F0 | read-write ! | primary | demoted
> node_14 | 14 | worker04:5432 | 14D/E54FE998 | read-write | wait_primary | wait_primary

So if you set `node_14` as your primary in your coordinator, it should work and it actually does work on both reads and writes? Can you check and let me know?

**Comment by serkancoban** [comment] 2021-06-12 18:02
Yes It is working, we are already tested it.  It is also explained here in detail: [pg_autofailover-tutorial](https://pg-auto-failover.readthedocs.io/en/master/tutorial.html#cause-a-node-failure)

**Comment by Navid2zp** [comment] 2021-06-12 19:20
I pushed a fix and released a new version with the fix.

Can you check and verify that the problem is solved?

**Comment by serkancoban** [comment] 2021-06-14 06:01
It is not working, check the logs below

{"level":"error","ts":1623649540.650183,"caller":"logging/core.go:49","msg":"failedto get workers!","service":"core","dbname":"postgres","error":"pq: invalid input value for enum noderole: \"wait_primary\"","stacktrace":"github.com/Navid2zp/citus-failover/logging.(*Logger).GetWorkersFailed\n\t/home/runner/work/citus-failover/citus-failover/logging/core.go:49\ngithub.com/Navid2zp/citus-failover/core.(*database).validateWorkers\n\t/home/runner/work/citus-failover/citus-failover/core/tasks.go:31\ngithub.com/Navid2zp/citus-failover/core.(*database).monitor\n\t/home/runner/work/citus-failover/citus-failover/core/tasks.go:58"}

https://github.com/Navid2zp/citus-failover/blob/a1d00a6b6f17a9848d981ef89b257d407a6c981d/core/core.go#L98
here did you add 'wait_primary' also? That sql is failing because of it.

**Comment by Navid2zp** [comment] 2021-06-14 10:05
@serkancoban Removed that part. Check the new release.

**Comment by serkancoban** [comment] 2021-06-14 10:52
It is working as expected, thank you for your work.

**Comment by Navid2zp** [comment] 2021-06-14 11:20
No problem.
Thank you for both reporting and helping with the bug.

**Closed by Navid2zp** 2021-06-14 11:20 UTC
Labels: bug
